baseURL = 'https://justabandon.github.io/'
title = "record and share"
languageCode = 'en'
defaultcontentlanguage = "en"
theme = "hugo-coder"
pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  author = "Just Abandon"
  description = "record and share"
  keywords = "blog,developer,personal"
  avatarurl = "images/nothing.png"
  colorScheme="auto"

[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/JustAbandon/"

[[params.social]]
  name = "Email"
  icon = "fa fa-envelope-o fa-4x"
  weight = 2
  url = "mailto:just_abandon@protonmail.com"


[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"

[[menu.main]]
  name = "Chat"
  weight = 3
  url = "chat/"

[[menu.main]]
  name = "Images"
  weight = 4
  url = "images/"